Update seeker.yml

diff --git a/.github/workflows/seeker.yml b/.github/workflows/seeker.yml
--- a/.github/workflows/seeker.yml
+++ b/.github/workflows/seeker.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     
     env:
-      SEEKER_SERVER_URL: https://seeker-server-host:8443
+      SEEKER_SERVER_URL: https://testing.seeker.synopsys.com:8443
       SEEKER_PROJECT_KEY: HIPPOTECH-GITHUB
       SEEKER_COMPLIANCE_FAIL_BUILD: true
 
@@ -18,10 +18,11 @@ jobs:
       - uses: actions/checkout@v2
       
       - name: Set up JDK 11
-      uses: actions/setup-java@v3  
-      with:
-        java-version: '11'
-        distribution: 'adopt'
+      - uses: actions/checkout@v3
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'adopt'
       
       - name: Cache Maven packages
         uses: actions/cache@v2
@@ -31,65 +32,64 @@ jobs:
           restore-keys: ${{ runner.os }}-m2
 
       - name: Build with Maven
-      run: mvn -DskipTests=true package
+        run: mvn -DskipTests=true package
 
       - name: Add Seeker Agent
-      run: |
-        sh -c "$(curl -X GET -fsSL --header 'Accept: application/x-sh'$SEEKER_SERVER_URL'/rest/api/latest/installers/agents/scripts/JAVA?osFamily=LINUX&downloadWith=curl&projectKey='$SEEKER_PROJECT_KEY'&webServer=OTHER&      flavor=DEFAULT&agentName=&accessToken=')"
-        echo "JAVA_TOOL_OPTIONS=-javaagent:./seeker/seeker-agent.jar" >> $GITHUB_ENV
+        run: |
+          sh -c "$(curl -X GET -fsSL --header 'Accept: application/x-sh'$SEEKER_SERVER_URL'/rest/api/latest/installers/agents/scripts/JAVA?osFamily=LINUX&downloadWith=curl&projectKey='$SEEKER_PROJECT_KEY'&webServer=OTHER&      flavor=DEFAULT&agentName=&accessToken=')"
+          echo "JAVA_TOOL_OPTIONS=-javaagent:./seeker/seeker-agent.jar" >> $GITHUB_ENV
 
       - name: Start HippoTech App for Testing
-      run: ./scripts/start.sh
+        run: ./scripts/start.sh
 
       - name: Use Node.js 12.x
-      uses: actions/setup-node@v2
-      with:
+        uses: actions/setup-node@v2
+        with:
         node-version: 12.x
         cache: 'npm'
 
-    - name: Functional Tests
-    uses: cypress-io/github-action@v2
+      - name: Functional Tests
+        uses: cypress-io/github-action@v2
 
-    - name: Shut Down HippoTech App
-    run: ./scripts/stop.sh
+      - name: Shut Down HippoTech App
+        run: ./scripts/stop.sh
 
-    - name: Generate Seeker Reports
-    run: |
-        curl -s -X 'GET' $SEEKER_SERVER_URL'/rest/api/latest/reports/compliances/\export?projectKeys='$SEEKER_PROJECT_KEY \
-        -H 'accept: application/pdf' \
-        -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
-        -H 'RequestSource: swagger' --output compliance-report.pdf
-        curl -s -X 'GET' $SEEKER_SERVER_URL'/rest/api/latest/vulnerabilities?\format=JSON&projectKeys='$SEEKER_PROJECT_KEY'&statuses=DETECTED&&minSeverity=HIGH' \
-        -H 'accept: text/plain' \
-        -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
-        -H 'RequestSource: swagger' | jq 'map(.ItemKey + " " + .VulnerabilityName + " URL:
-" + .SeekerServerLink)'
+      - name: Generate Seeker Reports
+        run: |
+          curl -s -X 'GET' $SEEKER_SERVER_URL'/rest/api/latest/reports/compliances/\export?projectKeys='$SEEKER_PROJECT_KEY \
+          -H 'accept: application/pdf' \
+          -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
+          -H 'RequestSource: swagger' --output compliance-report.pdf
+          curl -s -X 'GET' $SEEKER_SERVER_URL'/rest/api/latest/vulnerabilities?\format=JSON&projectKeys='$SEEKER_PROJECT_KEY'&statuses=DETECTED&&minSeverity=HIGH' \
+          -H 'accept: text/plain' \
+          -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
+          -H 'RequestSource: swagger' | jq 'map(.ItemKey + " " + .VulnerabilityName + " URL:" + .SeekerServerLink)'
+      
+      - name: Publish Seeker Reports
+        uses: actions/upload-artifact@v3
+        with:
+          name: Seeker Compliance Reports
+          path: |
+            compliance-report.pdf
 
-    - name: Publish Seeker Reports
-    uses: actions/upload-artifact@v2
-    with:
-      name: Seeker Compliance Reports
-      path: |
-        compliance-report.pdf
-
-    - name: Seeker Compliance Check
-    run: |
-      COMPLIANCE=`curl -s -X 'GET' \
-      $SEEKER_SERVER_URL'/rest/api/latest/projects/'$SEEKER_PROJECT_KEY'/status' \
-      -H 'accept: application/json' \
-      -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
-      -H 'RequestSource: swagger'` | jq '.projectStatus.compliant'
-    if [ "$COMPLIANCE" = "true" ]; then
-      echo "Seeker Compliance Check Passed"
-    else
-      if [ "$SEEKER_COMPLIANCE_FAIL_BUILD" = "true" ]; then
-        echo "::error ::Seeker compliance check failed." && exit 1
-      else
-        echo "::warning ::Seeker compliance check failed."
-      fi
-    fi
-  - name: Publish Test Report
-  uses: mikepenz/action-junit-report@v2
-  with:
-    report_paths: '**/results/*.xml'
-    check_name: "test
+      - name: Seeker Compliance Check
+        run: |
+          COMPLIANCE=`curl -s -X 'GET' \
+            $SEEKER_SERVER_URL'/rest/api/latest/projects/'$SEEKER_PROJECT_KEY'/status' \
+            -H 'accept: application/json' \
+            -H "Authorization: ${{ secrets.SEEKER_API_TOKEN }}" \
+            -H 'RequestSource: swagger'` | jq '.projectStatus.compliant'
+          if [ "$COMPLIANCE" = "true" ]; then
+            echo "Seeker Compliance Check Passed"
+          else
+            if [ "$SEEKER_COMPLIANCE_FAIL_BUILD" = "true" ]; then
+              echo "::error ::Seeker compliance check failed." && exit 1
+            else
+              echo "::warning ::Seeker compliance check failed."
+            fi
+          fi
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v2
+        with:
+          report_paths: '**/results/*.xml'
+          check_name: "test
